wandb_version: 1

env_name:
  desc: null
  value: coinrun
instance_id:
  desc: null
  value: 0
num_iterations:
  desc: null
  value: 1000
exp_name:
  desc: null
  value: baseline
_wandb:
  desc: null
  value:
    python_version: 3.10.16
    cli_version: 0.15.12
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1757103227.992832
    t:
      1:
      - 2
      - 3
      - 12
      - 55
      2:
      - 2
      - 3
      - 12
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.10.16
      5: 0.15.12
      8:
      - 3
      - 5
      13: windows-amd64
