name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - alabaster=0.7.12=pyhd3eb1b0_0
  - anaconda-client=1.11.2=py310haa95532_0
  - anaconda-navigator=2.4.0=py310haa95532_0
  - anaconda-project=0.11.1=py310haa95532_0
  - anyio=3.5.0=py310haa95532_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py310h2bbff1b_0
  - arrow=1.2.3=py310haa95532_1
  - astroid=2.14.2=py310haa95532_0
  - astropy=5.1=py310h9128911_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - atomicwrites=1.4.0=py_0
  - attrs=22.1.0=py310haa95532_0
  - automat=20.2.0=py_0
  - autopep8=1.6.0=pyhd3eb1b0_1
  - babel=2.11.0=py310haa95532_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - backports=1.1=pyhd3eb1b0_0
  - backports.functools_lru_cache=1.6.4=pyhd3eb1b0_0
  - backports.tempfile=1.0=pyhd3eb1b0_1
  - backports.weakref=1.0.post1=py_1
  - bcrypt=3.2.0=py310h2bbff1b_1
  - beautifulsoup4=4.11.1=py310haa95532_0
  - binaryornot=0.4.4=pyhd3eb1b0_1
  - black=22.6.0=py310haa95532_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - bokeh=2.4.3=py310haa95532_0
  - boltons=23.0.0=py310haa95532_0
  - bottleneck=1.3.5=py310h9128911_0
  - brotli=1.0.9=h2bbff1b_7
  - brotli-bin=1.0.9=h2bbff1b_7
  - brotlipy=0.7.0=py310h2bbff1b_1002
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2025.1.31=h56e8100_0
  - certifi=2025.1.31=pyhd8ed1ab_0
  - cffi=1.15.1=py310h2bbff1b_3
  - cfitsio=3.470=h2bbff1b_7
  - chardet=4.0.0=py310haa95532_1003
  - charls=2.2.0=h6c2663c_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.4=py310haa95532_0
  - cloudpickle=2.0.0=pyhd3eb1b0_0
  - clyent=1.2.2=py310haa95532_1
  - colorama=0.4.6=py310haa95532_0
  - colorcet=3.0.1=py310haa95532_0
  - comm=0.1.2=py310haa95532_0
  - conda=23.3.1=py310haa95532_0
  - conda-build=3.24.0=py310haa95532_0
  - conda-content-trust=0.1.3=py310haa95532_0
  - conda-pack=0.6.0=pyhd3eb1b0_0
  - conda-package-handling=2.0.2=py310haa95532_0
  - conda-package-streaming=0.7.0=py310haa95532_0
  - conda-repo-cli=1.0.41=py310haa95532_0
  - conda-token=0.4.0=pyhd3eb1b0_0
  - conda-verify=3.4.2=py_1
  - console_shortcut=0.1.1=4
  - constantly=15.1.0=py310haa95532_0
  - contourpy=1.0.5=py310h59b6b97_0
  - cookiecutter=1.7.3=pyhd3eb1b0_0
  - cryptography=39.0.1=py310h21b164f_0
  - cssselect=1.1.0=pyhd3eb1b0_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cytoolz=0.12.0=py310h2bbff1b_0
  - daal4py=2023.0.2=py310hf497b98_0
  - dal=2023.0.1=h59b6b97_26646
  - dask=2022.7.0=py310haa95532_0
  - dask-core=2022.7.0=py310haa95532_0
  - datashader=0.14.4=py310haa95532_0
  - datashape=0.5.4=py310haa95532_1
  - debugpy=1.5.1=py310hd77b12b_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - diff-match-patch=20200713=pyhd3eb1b0_0
  - dill=0.3.6=py310haa95532_0
  - distributed=2022.7.0=py310haa95532_0
  - docstring-to-markdown=0.11=py310haa95532_0
  - docutils=0.18.1=py310haa95532_3
  - entrypoints=0.4=py310haa95532_0
  - et_xmlfile=1.1.0=py310haa95532_0
  - executing=0.8.3=pyhd3eb1b0_0
  - filelock=3.9.0=py310haa95532_0
  - flake8=6.0.0=py310haa95532_0
  - flask=2.2.2=py310haa95532_0
  - flit-core=3.6.0=pyhd3eb1b0_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=hdaf720e_2
  - fsspec=2022.11.0=py310haa95532_0
  - future=0.18.3=py310haa95532_0
  - gensim=4.3.0=py310h4ed8f06_0
  - giflib=5.2.1=h8cc25b3_3
  - glib=2.82.2=h3d4babf_1
  - glib-tools=2.82.2=h4394cf3_1
  - glob2=0.7=pyhd3eb1b0_0
  - greenlet=2.0.1=py310hd77b12b_0
  - gst-plugins-base=1.24.7=hb0a98b8_0
  - gstreamer=1.24.7=h5006eae_0
  - heapdict=1.0.1=pyhd3eb1b0_0
  - holoviews=1.15.4=py310haa95532_0
  - huggingface_hub=0.10.1=py310haa95532_0
  - hvplot=0.8.2=py310haa95532_0
  - hyperlink=21.0.0=pyhd3eb1b0_0
  - icc_rt=2022.1.0=h6049295_2
  - icu=75.1=he0c23c2_0
  - idna=3.4=py310haa95532_0
  - imageio=2.26.0=py310haa95532_0
  - imagesize=1.4.1=py310haa95532_0
  - imbalanced-learn=0.10.1=py310haa95532_0
  - importlib-metadata=4.11.3=py310haa95532_0
  - importlib_metadata=4.11.3=hd3eb1b0_0
  - incremental=21.3.0=pyhd3eb1b0_0
  - inflection=0.5.1=py310haa95532_0
  - iniconfig=1.1.1=pyhd3eb1b0_0
  - intake=0.6.7=py310haa95532_0
  - intel-openmp=2021.4.0=haa95532_3556
  - intervaltree=3.1.0=pyhd3eb1b0_0
  - ipykernel=6.19.2=py310h9909e9c_0
  - ipython=8.10.0=py310haa95532_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.5=pyhd3eb1b0_1
  - isort=5.9.3=pyhd3eb1b0_0
  - itemadapter=0.3.0=pyhd3eb1b0_0
  - itemloaders=1.0.4=pyhd3eb1b0_1
  - itsdangerous=2.0.1=pyhd3eb1b0_0
  - jedi=0.18.1=py310haa95532_1
  - jellyfish=0.9.0=py310h2bbff1b_0
  - jinja2=3.1.2=py310haa95532_0
  - jinja2-time=0.2.0=pyhd3eb1b0_3
  - jmespath=0.10.0=pyhd3eb1b0_0
  - joblib=1.1.1=py310haa95532_0
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonpatch=1.32=pyhd3eb1b0_0
  - jsonpointer=2.1=pyhd3eb1b0_0
  - jsonschema=4.17.3=py310haa95532_0
  - jupyter=1.0.0=py310haa95532_8
  - jupyter_client=7.3.4=py310haa95532_0
  - jupyter_console=6.6.2=py310haa95532_0
  - jupyter_core=5.2.0=py310haa95532_0
  - jupyter_server=1.23.4=py310haa95532_0
  - jupyterlab=3.5.3=py310haa95532_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.19.0=py310haa95532_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - jxrlib=1.1=he774522_2
  - keyring=23.4.0=py310haa95532_0
  - kiwisolver=1.4.4=py310hd77b12b_0
  - krb5=1.21.3=hdf4eb48_0
  - lazy-object-proxy=1.6.0=py310h2bbff1b_0
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h63175ca_0
  - libaec=1.0.4=h33f27b4_1
  - libarchive=3.7.7=h88ece9c_0
  - libbrotlicommon=1.0.9=h2bbff1b_7
  - libbrotlidec=1.0.9=h2bbff1b_7
  - libbrotlienc=1.0.9=h2bbff1b_7
  - libclang13=19.1.7=default_ha5278ca_1
  - libdeflate=1.23=h9062f6e_0
  - libffi=3.4.2=hd77b12b_6
  - libgcc=14.2.0=h1383e82_2
  - libglib=2.82.2=h7025463_1
  - libgomp=14.2.0=h1383e82_2
  - libiconv=1.18=h135ad9c_1
  - libintl=0.22.5=h5728263_3
  - libintl-devel=0.22.5=h5728263_3
  - libjpeg-turbo=3.0.0=hcfcfb64_1
  - liblief=0.12.3=hd77b12b_0
  - liblzma=5.6.4=h2466b09_0
  - libogg=1.3.5=h2bbff1b_1
  - libpng=1.6.47=had7236b_0
  - libsodium=1.0.18=h62dcd97_0
  - libspatialindex=1.9.3=h6c2663c_0
  - libsqlite=3.49.1=h67fdade_1
  - libtiff=4.7.0=h797046b_3
  - libuv=1.44.2=h2bbff1b_0
  - libvorbis=1.3.7=he774522_0
  - libwebp-base=1.5.0=h3b0e114_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_9
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.13.6=he286e8c_0
  - libxslt=1.1.39=h3df6e99_0
  - libzlib=1.3.1=h2466b09_2
  - libzlib-wapi=1.3.1=h2466b09_2
  - libzopfli=1.0.3=ha925a31_0
  - llvmlite=0.39.1=py310h23ce68f_0
  - locket=1.0.0=py310haa95532_0
  - lxml=5.3.1=py310hb043844_0
  - lz4=3.1.3=py310h2bbff1b_0
  - lz4-c=1.9.4=h2bbff1b_0
  - lzo=2.10=he774522_2
  - m2-conda-epoch=20230914=0_x86_64
  - m2-patch=2.7.6.2=hd8ed1ab_0
  - markdown=3.4.1=py310haa95532_0
  - markupsafe=2.1.1=py310h2bbff1b_0
  - matplotlib=3.7.0=py310haa95532_0
  - matplotlib-base=3.7.0=py310h4ed8f06_0
  - matplotlib-inline=0.1.6=py310haa95532_0
  - mccabe=0.7.0=pyhd3eb1b0_0
  - menuinst=1.4.19=py310h59b6b97_0
  - mistune=0.8.4=py310h2bbff1b_1000
  - mkl=2021.4.0=haa95532_640
  - mkl-service=2.4.0=py310h2bbff1b_0
  - mkl_fft=1.3.1=py310ha0764ea_0
  - mkl_random=1.2.2=py310h4ed8f06_0
  - mock=4.0.3=pyhd3eb1b0_0
  - mpmath=1.2.1=py310haa95532_0
  - msgpack-python=1.0.3=py310h59b6b97_0
  - multipledispatch=0.6.0=py310haa95532_0
  - munkres=1.1.4=py_0
  - mypy_extensions=0.4.3=py310haa95532_1
  - navigator-updater=0.3.0=py310haa95532_0
  - nbclassic=0.5.2=py310haa95532_0
  - nbclient=0.5.13=py310haa95532_0
  - nbconvert=6.5.4=py310haa95532_0
  - nbformat=5.7.0=py310haa95532_0
  - nest-asyncio=1.5.6=py310haa95532_0
  - networkx=2.8.4=py310haa95532_0
  - ninja=1.10.2=haa95532_5
  - ninja-base=1.10.2=h6d14046_5
  - nltk=3.7=pyhd3eb1b0_0
  - notebook=6.5.2=py310haa95532_0
  - notebook-shim=0.2.2=py310haa95532_0
  - numba=0.56.4=py310h4ed8f06_0
  - numexpr=2.8.4=py310hd213c9f_0
  - numpydoc=1.5.0=py310haa95532_0
  - openjpeg=2.5.3=h4d64b90_0
  - openpyxl=3.0.10=py310h2bbff1b_0
  - openssl=3.4.1=ha4e3fda_0
  - packaging=22.0=py310haa95532_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - panel=0.14.3=py310haa95532_0
  - param=1.12.3=py310haa95532_0
  - paramiko=2.8.1=pyhd3eb1b0_0
  - parsel=1.6.0=py310haa95532_0
  - parso=0.8.3=pyhd3eb1b0_0
  - partd=1.2.0=pyhd3eb1b0_1
  - pathlib=1.0.1=pyhd3eb1b0_1
  - pathspec=0.10.3=py310haa95532_0
  - patsy=0.5.3=py310haa95532_0
  - pcre=8.45=hd77b12b_0
  - pcre2=10.44=h3d7b363_2
  - pep8=1.7.1=py310haa95532_1
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=11.1.0=py310h9595edc_0
  - pip=22.3.1=py310haa95532_0
  - pkginfo=1.9.6=py310haa95532_0
  - platformdirs=2.5.2=py310haa95532_0
  - plotly=5.9.0=py310haa95532_0
  - pluggy=1.0.0=py310haa95532_1
  - ply=3.11=py310haa95532_0
  - pooch=1.4.0=pyhd3eb1b0_0
  - powershell_shortcut=0.0.1=3
  - poyo=0.5.0=pyhd3eb1b0_0
  - prometheus_client=0.14.1=py310haa95532_0
  - prompt-toolkit=3.0.36=py310haa95532_0
  - prompt_toolkit=3.0.36=hd3eb1b0_0
  - protego=0.1.16=py_0
  - psutil=5.9.0=py310h2bbff1b_0
  - pthread-stubs=0.4=h0e40799_1002
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - py=1.11.0=pyhd3eb1b0_0
  - py-lief=0.12.3=py310hd77b12b_0
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pycodestyle=2.10.0=py310haa95532_0
  - pycosat=0.6.4=py310h2bbff1b_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyct=0.5.0=py310haa95532_0
  - pydispatcher=2.0.5=py310haa95532_2
  - pydocstyle=6.3.0=py310haa95532_0
  - pyerfa=2.0.0=py310h2bbff1b_0
  - pyflakes=3.0.1=py310haa95532_0
  - pyhamcrest=2.0.2=pyhd3eb1b0_2
  - pyjwt=2.4.0=py310haa95532_0
  - pylint=2.16.2=py310haa95532_0
  - pyls-spyder=0.4.0=pyhd3eb1b0_0
  - pynacl=1.5.0=py310h8cc25b3_0
  - pyodbc=4.0.34=py310hd77b12b_0
  - pyopenssl=23.0.0=py310haa95532_0
  - pyparsing=3.0.9=py310haa95532_0
  - pyqt=5.15.7=py310hd77b12b_0
  - pyqt5-sip=12.11.0=py310hd77b12b_0
  - pyqtwebengine=5.15.7=py310hd77b12b_0
  - pyrsistent=0.18.0=py310h2bbff1b_0
  - pysocks=1.7.1=py310haa95532_0
  - pytest=7.1.2=py310haa95532_0
  - python=3.10.16=h37870fc_1_cpython
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=py310haa95532_0
  - python-libarchive-c=2.9=pyhd3eb1b0_1
  - python-lsp-black=1.2.1=py310haa95532_0
  - python-lsp-jsonrpc=1.0.0=pyhd3eb1b0_0
  - python-lsp-server=1.7.1=py310haa95532_0
  - python-slugify=5.0.2=pyhd3eb1b0_0
  - python-snappy=0.6.1=py310hd77b12b_0
  - python_abi=3.10=5_cp310
  - pytoolconfig=1.2.5=py310haa95532_1
  - pytorch=1.12.1=cpu_py310h5e1f01c_1
  - pytz=2022.7=py310haa95532_0
  - pyviz_comms=2.0.2=pyhd3eb1b0_0
  - pywavelets=1.4.1=py310h2bbff1b_0
  - pywin32=305=py310h2bbff1b_0
  - pywin32-ctypes=0.2.0=py310haa95532_1000
  - pywinpty=2.0.10=py310h5da7b33_0
  - pyyaml=6.0=py310h2bbff1b_1
  - pyzmq=23.2.0=py310hd77b12b_0
  - qdarkstyle=3.0.2=pyhd3eb1b0_0
  - qt-main=5.15.15=h9151539_2
  - qt-webengine=5.15.9=h5bd16bc_7
  - qtpy=2.2.0=py310haa95532_0
  - qtwebkit=5.212=hbc9c816_18
  - queuelib=1.5.0=py310haa95532_0
  - regex=2022.7.9=py310h2bbff1b_0
  - requests=2.28.1=py310haa95532_0
  - requests-file=1.5.1=pyhd3eb1b0_0
  - requests-toolbelt=0.9.1=pyhd3eb1b0_0
  - rope=1.7.0=py310haa95532_0
  - rtree=1.0.1=py310h2eaa2aa_0
  - ruamel.yaml=0.17.21=py310h2bbff1b_0
  - ruamel.yaml.clib=0.2.6=py310h2bbff1b_1
  - ruamel_yaml=0.17.21=py310h2bbff1b_0
  - scikit-image=0.19.3=py310hd77b12b_1
  - scikit-learn=1.2.1=py310hd77b12b_0
  - scikit-learn-intelex=2023.0.2=py310haa95532_0
  - scrapy=2.8.0=py310haa95532_0
  - seaborn=0.12.2=py310haa95532_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - service_identity=18.1.0=pyhd3eb1b0_1
  - setuptools=65.6.3=py310haa95532_0
  - sip=6.6.2=py310hd77b12b_0
  - six=1.16.0=pyhd3eb1b0_1
  - smart_open=5.2.1=py310haa95532_0
  - snappy=1.1.9=h6c2663c_0
  - sniffio=1.2.0=py310haa95532_1
  - snowballstemmer=2.2.0=pyhd3eb1b0_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - soupsieve=2.3.2.post1=py310haa95532_0
  - sphinx=5.0.2=py310haa95532_0
  - sphinxcontrib-applehelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-devhelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-htmlhelp=2.0.0=pyhd3eb1b0_0
  - sphinxcontrib-jsmath=1.0.1=pyhd3eb1b0_0
  - sphinxcontrib-qthelp=1.0.3=pyhd3eb1b0_0
  - sphinxcontrib-serializinghtml=1.1.5=pyhd3eb1b0_0
  - spyder=5.4.1=py310haa95532_0
  - spyder-kernels=2.4.1=py310haa95532_0
  - sqlalchemy=1.4.39=py310h2bbff1b_0
  - sqlite=3.40.1=h2bbff1b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - statsmodels=0.13.5=py310h9128911_1
  - sympy=1.11.1=py310haa95532_0
  - tabulate=0.8.10=py310haa95532_0
  - tbb=2021.7.0=h59b6b97_0
  - tbb4py=2021.7.0=py310h59b6b97_0
  - tblib=1.7.0=pyhd3eb1b0_0
  - tenacity=8.0.1=py310haa95532_1
  - terminado=0.17.1=py310haa95532_0
  - text-unidecode=1.3=pyhd3eb1b0_0
  - textdistance=4.2.1=pyhd3eb1b0_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - three-merge=0.1.1=pyhd3eb1b0_0
  - tifffile=2024.12.12=py310haa95532_0
  - tinycss2=1.2.1=py310haa95532_0
  - tk=8.6.13=h5226925_1
  - tldextract=3.2.0=pyhd3eb1b0_0
  - tokenizers=0.11.4=py310he5181cf_1
  - toml=0.10.2=pyhd3eb1b0_0
  - tomli=2.0.1=py310haa95532_0
  - tomlkit=0.11.1=py310haa95532_0
  - toolz=0.12.0=py310haa95532_0
  - tornado=6.1=py310h2bbff1b_0
  - tqdm=4.64.1=py310haa95532_0
  - traitlets=5.7.1=py310haa95532_0
  - transformers=4.24.0=py310haa95532_0
  - twisted=22.2.0=py310h2bbff1b_1
  - twisted-iocpsupport=1.0.2=py310h2bbff1b_0
  - ucrt=10.0.22621.0=h57928b3_1
  - ujson=5.4.0=py310hd77b12b_0
  - unidecode=1.2.0=pyhd3eb1b0_0
  - urllib3=1.26.14=py310haa95532_0
  - vc=14.2=h21ff451_1
  - vc14_runtime=14.42.34433=h6356254_24
  - vs2015_runtime=14.42.34433=hfef2bbc_24
  - w3lib=1.21.0=pyhd3eb1b0_0
  - watchdog=2.1.6=py310haa95532_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py310haa95532_1
  - websocket-client=0.58.0=py310haa95532_4
  - werkzeug=2.2.2=py310haa95532_0
  - whatthepatch=1.0.2=py310haa95532_0
  - wheel=0.38.4=py310haa95532_0
  - widgetsnbextension=3.5.2=py310haa95532_0
  - win_inet_pton=1.1.0=py310haa95532_0
  - wincertstore=0.2=py310haa95532_2
  - winpty=0.4.3=4
  - wrapt=1.14.1=py310h2bbff1b_0
  - xarray=2022.11.0=py310haa95532_0
  - xlwings=0.29.1=py310haa95532_0
  - xorg-libxau=1.0.12=h0e40799_0
  - xorg-libxdmcp=1.1.5=h0e40799_0
  - xz=5.2.10=h8cc25b3_1
  - yaml=0.2.5=he774522_0
  - yapf=0.31.0=pyhd3eb1b0_0
  - zeromq=4.3.4=hd77b12b_0
  - zfp=0.5.5=hd77b12b_6
  - zict=2.1.0=py310haa95532_0
  - zipp=3.11.0=py310haa95532_0
  - zlib=1.3.1=h2466b09_2
  - zlib-wapi=1.3.1=h2466b09_2
  - zope=1.0=py310haa95532_1
  - zope.interface=5.4.0=py310h2bbff1b_0
  - zstandard=0.19.0=py310h2bbff1b_0
  - zstd=1.5.7=hbeecb71_1
  - pip:
      - absl-py==2.1.0
      - annotated-types==0.7.0
      - astunparse==1.6.3
      - cachetools==5.5.0
      - dm-tree==0.1.8
      - docker-pycreds==0.4.0
      - docstring-parser==0.16
      - flatbuffers==24.3.25
      - fst-pso==1.8.1
      - fuzzytm==2.0.9
      - gast==0.4.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - glcontext==2.5.0
      - glfw==1.12.0
      - google-auth==2.37.0
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - grpcio==1.64.0
      - gym==0.26.2
      - gym-notices==0.0.8
      - gym3==0.3.3
      - h5py==3.14.0
      - imageio-ffmpeg==0.3.0
      - jax==0.4.30
      - jaxlib==0.4.30
      - keras==2.10.0
      - keras-preprocessing==1.1.2
      - libclang==18.1.1
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - miniful==0.0.6
      - ml-dtypes==0.4.1
      - moderngl==5.10.0
      - namex==0.0.8
      - numpy==1.24.4
      - oauthlib==3.2.2
      - opencv-python==4.10.0.84
      - opt-einsum==3.3.0
      - optree==0.11.0
      - pandas==1.5.3
      - pathtools==0.1.2
      - procgen==0.10.7
      - protobuf==3.19.6
      - pydantic==2.10.5
      - pydantic-core==2.27.2
      - pyfume==0.3.4
      - pygments==2.18.0
      - pylint-venv==2.3.0
      - python-version==0.0.2
      - qstylizer==0.2.2
      - qtawesome==1.2.2
      - qtconsole==5.4.0
      - requests-oauthlib==2.0.0
      - rich==13.7.1
      - rsa==4.9
      - scipy==1.10.1
      - sentry-sdk==2.20.0
      - setproctitle==1.3.4
      - shtab==1.7.1
      - simpful==2.12.0
      - smmap==5.0.2
      - tensorboard==2.10.1
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.10.0
      - tensorflow-estimator==2.10.0
      - tensorflow-gpu==2.10.0
      - tensorflow-intel==2.12.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - tensorflow-probability==0.18.0
      - termcolor==2.4.0
      - typing-extensions==4.12.2
      - tyro==0.8.4
      - tzdata==2024.2
      - wandb==0.15.12
prefix: C:\Users\Acer\anaconda3
